[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "lru-fastapi"
version = "0.1.0"
description = "LRU Cache (DLL+HashMap) with FastAPI"
readme = "README.md"
requires-python = ">=3.9"

[tool.setuptools.packages.find]
include = ["lru_cache", "api"]
